/** Entirely synthetic. No household record, source path or account identifier belongs to a real person. */
export function financeFixture() {
    const source = {
        file: "C:/synthetic/original.csv",
        sha256: "a".repeat(64),
        record: 2,
    };
    const accounts = [
        ["bank", "Compte courant", "bank"],
        ["card", "Carte de test", "credit-card"],
        ["rrsp", "REER de test", "brokerage"],
        ["gic", "CPG de test", "gic"],
    ].map(([accountId, alias, type]) => ({
        accountId,
        alias,
        type,
        currency: "CAD",
        observedBalanceCents: 500000,
        observedOn: "2026-10-09",
        identityEvidence: "Synthetic account selector",
    }));
    const transaction = (
        id,
        date,
        descriptionOriginal,
        debitCents,
        creditCents = null,
        accountId = "card",
        extra = {},
    ) => ({
        id,
        sourceRowId: id,
        matchingFingerprint: id,
        accountId,
        transactionDate: date,
        descriptionOriginal,
        currency: "CAD",
        debitCents,
        creditCents,
        signedOutflowCents: (debitCents ?? 0) - (creditCents ?? 0),
        status: "posted",
        occurrence: 1,
        reviewHints: [],
        source,
        ...extra,
    });
    const bankActivities = [
        transaction("groceries", "2026-04-15", "SAFEWAY SYNTHETIC", 12450),
        transaction("refund", "2026-04-16", "SAFEWAY SYNTHETIC", null, 2450),
        transaction("restaurant", "2026-05-10", "SYNTHETIC RESTAURANT", 5400),
        transaction(
            "mortgage",
            "2026-06-01",
            "SYNTHETIC MORTGAGE",
            220000,
            null,
            "bank",
        ),
        transaction(
            "transfer",
            "2026-06-03",
            "TRANSFER TO SYNTHETIC",
            50000,
            null,
            "bank",
        ),
        transaction(
            "repayment",
            "2026-06-05",
            "PAYMENT THANK YOU",
            null,
            50000,
        ),
        transaction(
            "childcare",
            "2026-07-02",
            "TWIG + OWL",
            45000,
            null,
            "bank",
        ),
        transaction(
            "unknown-credit",
            "2026-07-05",
            "SYNTHETIC UNKNOWN",
            null,
            1000,
            "bank",
        ),
        transaction("subscription", "2026-08-10", "SPOTIFY SYNTHETIC", 1800),
        transaction("subscription2", "2026-09-10", "SPOTIFY SYNTHETIC", 2000),
        transaction(
            "repeat1",
            "2026-09-11",
            "CAFE SYNTHETIC",
            500,
            null,
            "card",
            { matchingFingerprint: "same", occurrence: 1 },
        ),
        transaction(
            "repeat2",
            "2026-09-11",
            "CAFE SYNTHETIC",
            500,
            null,
            "card",
            { matchingFingerprint: "same", occurrence: 2 },
        ),
        transaction("pending-month", "2026-10-02", "SAFEWAY SYNTHETIC", 999),
    ];
    const brokerageActivities = [
        ["contribution", "CONT", 100000],
        ["transfer-in", "TFR-IN", 200000],
        ["grant", "CESG", 20000],
        ["buy", "BUY", -100000],
        ["drip", "DRIP", 0],
        ["fee", "MGTFEE", -1000],
        ["tax", "GST", -50],
    ].map(([id, actionOriginal, netCashCents]) => ({
        id,
        accountId: "rrsp",
        tradeDate: "2026-09-15",
        settleDate: "2026-09-17",
        descriptionOriginal: "Synthetic security activity",
        actionOriginal,
        netCashCents,
        commissionCents: null,
        quantityDecimal: "10.5",
        priceDecimal: null,
        currency: "CAD",
        status: "posted",
        source,
    }));
    return {
        schema: "familyhub.td.preparation.v1",
        collectedOn: "2026-10-09",
        scope: { from: "2026-03-01", to: "2026-10-09" },
        accounts,
        bankActivities,
        brokerageActivities,
        pendingActivities: [{ status: "pending" }],
        holdingsSnapshots: [
            {
                accountId: "rrsp",
                bankAsOf: "2026-10-09 12:00:00",
                currency: "CAD",
                cashCents: 50000,
                investmentsCents: 450000,
                totalValueCents: 500000,
                positions: [
                    {
                        Symbol: "DEMO",
                        Description: "Fonds synthétique",
                        Quantity: "100",
                        Price: "45.00",
                        "Market Value": "4500.00",
                        "Book Cost": "4000.00",
                    },
                ],
                source,
            },
        ],
        performanceSnapshots: [
            {
                accountId: "rrsp",
                actualStart: "2026-04-01",
                actualEnd: "2026-09-30",
                status: "Synthetic portal series; method not established",
                trend: [
                    { date: "2026-04-01", endingBalanceCents: 100000 },
                    { date: "2026-09-30", endingBalanceCents: 490000 },
                ],
            },
        ],
        gicDetails: {
            accountId: "gic",
            principalCents: 500000,
            currency: "CAD",
            issueDate: "2026-08-01",
            maturityDate: "2027-08-01",
            annualRatePercentDecimal: "2.50",
            evidence: "Synthetic deposit statement",
        },
        financialDocumentFacts: {
            feesReports: [
                {
                    accountId: "rrsp",
                    from: "2025-01-01",
                    to: "2025-12-31",
                    currency: "CAD",
                    totalPaidCents: 2000,
                    status: "Synthetic annual report",
                    source,
                },
            ],
        },
        coverage: accounts.map((a) => ({
            accountId: a.accountId,
            earliest: a.accountId === "card" ? "2026-03-11" : "2026-03-01",
            latest: "2026-10-09",
            coverageWarning:
                a.accountId === "card"
                    ? "Older card history unavailable"
                    : null,
        })),
        limits: ["Synthetic coverage only"],
        unknownExtension: { retain: "original source extension" },
    };
}
